feat: prevent focus on disabled dates
Sqrrl/wc-datepicker pull request #28
Opened 2024-07-02 12:51 UTC by remischwartz

Hi,

This is a proposal to prevent focus on disabled dates (cf #25 ).
 I struggled to find a satisfying behavior, and eventually settled on the following one :
- up/down/left/right arrows will look for the first available (not disabled) date in the corresponding direction, up to a maximum difference in days (customizable via the `max-search-days` attribute)
- Home/End will look for the first/last available date in the current month
- Page up/down will look for the first available date in the previous/next month
- Shift + Page up/down will look for the next available date a year before/after the current date

Please let me know what you think.

2024-07-08 13:32 UTC, Sqrrl requested changes
Thanks for the PR. Found one or two issues.

2024-07-08 13:32 UTC, Sqrrl commented on src/components/wc-datepicker/wc-datepicker.tsx
> +                              !this.disableDate(day) &&
Suggestion: Use `isDisabled` from line 747 to not execute the `disableDate` function twice.

2024-07-08 13:32 UTC, Sqrrl commented on src/components/wc-datepicker/wc-datepicker.tsx
> +        );
Issue: Something seems off here. I've tried these settings: 
```js
datepicker.maxSearchDays = 1000;

datepicker.disableDate = (date) => {
  return (
    date.getDay() === 6 ||
    date.getDay() === 0 ||
    date.getDate() === 15 ||
    date.getYear() === 124
  );
};
```
- Select a day in December 2023
- Hit Page Down or Shift + Page Down
- ⛔️ Nothing happens

I assume the same Page Up has the same issue. Maybe one or two tests would be helpful.

2024-08-01 14:45 UTC, remischwartz commented on src/components/wc-datepicker/wc-datepicker.tsx
> +        );
This has to do with the new behavior where disabled dates are no longer focusable.
When hitting Page Down or Shift + Page Down, the date picker will look for the next available date in next month or next year. But if there is none (in your exemple, the whole 2024 year is disabled), the currentDate is not changed.

Do you see another approach that could be taken ?

2024-09-20 12:59 UTC, remischwartz commented on src/components/wc-datepicker/wc-datepicker.tsx
> +                              !this.disableDate(day) &&
I made the change ✅

2024-09-20 13:13 UTC, Sqrrl approved these changes

2024-09-20 13:13 UTC, merged

2024-09-20 13:20 UTC, Sqrrl commented
Thanks again. Released as v0.6.0. https://github.com/Sqrrl/wc-datepicker/releases/tag/v0.6.0